Description:
  Koki Mitsunami / Cloud DevOps Engineer Nanodegree
  Deploy a high-availability web app using CloudFormation 

Parameters:
# whatever you consider a changing value, put it as a parameter instead of hard-coding it into your script
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this
    Type: String
    Default: 10.0.0.0/16

Resources:
  #instace profile contains the IAM Role name(s) that we want to associate to our auto scaling EC2 Servers

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      #VpnGatewayId: String

  #ProfileWithRolesForOurApp:
  #  Type: AWS::IAM::InstanceProfile
  #  Properties: 
  #    Roles:
  #      - UdacityS3ReadOnlyEC2
  
          ##!/bin/bash
          #apt-get update -y
          #apt-get install unzip awscli -y
          #apt-get install apache2 -y
          #systemctl start apache2.service
          #cd /var/www/html
          #aws s3 cp s3://udacity-demo-1/udacity.zip .
          #unzip -o udacity.zip
  #Outputs: 
  #Bonus points for useful outputs!
